export const siteConfig = {
    title: "JSE NEXT APP",
    description: "Generated by create next app",
    navigation: [
        { name: "About", href: "/about" },
        { name: "Contacts", href: "/contacts" },
    ],
}